### ISSUE TITLE
how to enable desktop icons

### ISSUE THREAD

**Issue by ghost** [MoonLGH/MoonLGH.github.io#2]
h

**Comment by kkrsharma11** [comment]
tell me in a script i use it for stupid things

**Comment by MoonLGH** [comment]
wdym ?

**Comment by kkrsharma11** [comment]
How to install full desktop? And I want service systemd start command run successful or systemctl service start

**Comment by kkrsharma11** [comment]
![Screenshot 2023-07-10 143728](https://github.com/MoonLGH/MoonLGH.github.io/assets/116044074/d8691c40-41d3-4d96-8f36-c15ce8f249c5)

**Comment by ghost** [comment]
qaf
